In [1]:
import pandas as pd

In [2]:
snp500_instruments = pd.read_csv("/Users/pankajti/dev/git/event-driven-narrative-trading/icaif_2026/data/snp_500_instruments.csv")

In [3]:
snp500_instruments

,id,con_id,symbol,market,exchange,primary_exchange,currency,country,sector,industry,sub_industry,long_name,is_active,updated_at
0,8,265768,ADBE,US,SMART,NASDAQ,USD,NaN,Technology,Software,Electronic Forms,ADOBE INC,True,2026-06-13 22:32:43.945
1,9,4157,ADI,US,SMART,NASDAQ,USD,NaN,Technology,Semiconductors,Electronic Compo-Semicon,ANALOG DEVICES INC,True,2026-06-13 22:32:43.945
2,10,4165,ADM,US,SMART,NYSE,USD,NaN,"Consumer, Non-cyclical",Agriculture,Agricultural Operations,ARCHER-DANIELS-MIDLAND CO,True,2026-06-13 22:32:43.945
3,11,4661,ADP,US,SMART,NASDAQ,USD,NaN,"Consumer, Non-cyclical",Commercial Services,Commercial Services,AUTOMATIC DATA PROCESSING,True,2026-06-13 22:32:43.945
4,12,265681,ADSK,US,SMART,NASDAQ,USD,NaN,Technology,Software,Computer Aided Design,AUTODESK INC,True,2026-06-13 22:32:43.945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,490,454859695,VTRS,US,SMART,NASDAQ,USD,NaN,"Consumer, Non-cyclical",Pharmaceuticals,Medical-Generic Drugs,VIATRIS INC,True,2026-06-13 22:32:43.945
512,491,4901,VZ,US,SMART,NYSE,USD,NaN,Communications,Telecommunications,Telephone-Integrated,VERIZON COMMUNICATIONS INC,True,2026-06-13 22:32:43.945
513,492,661633,WAB,US,SMART,NYSE,USD,NaN,Industrial,Machinery-Diversified,Machinery-General Indust,WABTEC CORP,True,2026-06-13 22:32:43.945
514,498,207739931,WELL,US,SMART,NYSE,USD,NaN,Financial,REITS,REITS-Health Care,WELLTOWER INC,True,2026-06-13 22:32:43.945
515,513,3206042,YUM,US,SMART,NYSE,USD,NaN,"Consumer, Cyclical",Retail,Retail-Restaurants,YUM! BRANDS INC,True,2026-06-13 22:32:43.945

In [4]:
snp500_instruments.columns

Index(['id', 'con_id', 'symbol', 'market', 'exchange', 'primary_exchange',
       'currency', 'country', 'sector', 'industry', 'sub_industry',
       'long_name', 'is_active', 'updated_at'],
      dtype='object')

In [7]:
snp500_instruments = snp500_instruments[['symbol','sector', 'industry', 'sub_industry']]

In [8]:
snp500_instruments.describe()

       symbol                  sector industry         sub_industry
count     516                     516      516                  516
unique    516                       9       59                  187
top      ADBE  Consumer, Non-cyclical    REITS  Electric-Integrated
freq        1                     105       29                   21